trigger:
  - none

variables:
  buildConfiguration: Release

parameters:
- name: vmImageName
  displayName: Select only for MS-Hosted
  type: string
  default: 'windows-latest'

- name: agentPoolName
  displayName: Select only for Self-Hosted
  type: string
  default: 'null'
  values:
  - HostMachine-Pool
  - null

- name: agentMachine
  displayName: Select Agent Machine for Self-hosted
  type: string
  default: LOKESHA-D
  values:
  - LOKESHA-D
  - LOKESHA-C

jobs:  
  - job: 
    ${{ if ne(parameters.agentPoolName, 'null')}}:
      pool:
        name: ${{ parameters.agentPoolName }}
        demands:
        - agent.name -equals ${{ parameters.agentMachine }}
    ${{ if eq(parameters.agentPoolName, 'null')}}:
      pool:
        vmImage: ${{ parameters.vmImageName }}
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)' 
