# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: windows-latest

parameters:
  - name: BASE_URL
    displayName: Application URL
    type: string
    default: "https://google.com"
    values:
      - "https://google.com"
steps:
- script: |
    echo "Env BASE_URL: %BASE_URL%"
    set BASE_URL=${{ parameters.BASE_URL }}
    echo "Locally Set BASE_URL: %BASE_URL%"
  env:
    BASE_URL: ${{ parameters.BASE_URL }}
  displayName: 'Set and Override BASE_URL'