# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: windows-latest

parameters:
  - name: BASE_URL
    displayName: Application URL
    type: string
    default: "https://loantapes-brave-dev-staging.azurewebsites.net/brave/"
    values:
      - "https://loantapes-brave-dev-staging.azurewebsites.net/brave/"
steps:
- script: |
    echo "Parameter value for BASE_URL: ${{ parameters.BASE_URL }}"
    set BASE_URL=${{ parameters.BASE_URL }}
    echo "Environment variable BASE_URL is set to: %BASE_URL%"
  # env: 
  #   BASE_URL: $(BASE_URL)
  displayName: 'Test for parameter'
